# Travis CI Configuration file
# @link https://travis-ci.org/

# Using Java for the project
language: java
jdk:
  - oraclejdk8
  

script:
  # Unit and integration tests are run
  - mvn clean verify -f /home/travis/build/naveentak/mule_projects/personapi/pom.xml

deploy:
  provider: releases
  api_key: "f9e5fcb582834bb2ac42a0a33cce9e90ba2801e2"
  file: "/home/travis/build/naveentak/mule_projects/personapi/target/personapi-1.0.0-SNAPSHOT-mule-application.jar"
  skip_cleanup: true
  on:
    tags: false